theme: jekyll-theme-cayman
title: [IBM i PHP / PDO / ODBC Setup]
description: [These are setup instructions and examples of how to run PHP on your IBM OR connect your PHP application to an IBM i]
markdown: kramdown
# Google Analytics
google_analytics: G-R6DP03HY2E
